<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251116142727 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_status (name VARCHAR(255) NOT NULL, id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX order_status_name_idx ON order_status (name)');
        $this->addSql('CREATE TABLE supplier (name VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX supplier_name_idx ON supplier (name)');
        $this->addSql('CREATE UNIQUE INDEX supplier_phone_idx ON supplier (phone)');
        $this->addSql('DROP INDEX id_idx');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE order_status');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('CREATE UNIQUE INDEX id_idx ON user_role (id)');
    }
}
