<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251116171119 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "order" (created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address VARCHAR(255) NOT NULL, total_price DOUBLE PRECISION NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, shop_id SMALLINT NOT NULL, status_id SMALLINT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F52993984D16C4DD ON "order" (shop_id)');
        $this->addSql('CREATE INDEX IDX_F52993986BF700BD ON "order" (status_id)');
        $this->addSql('CREATE INDEX IDX_F5299398A76ED395 ON "order" (user_id)');
        $this->addSql('CREATE TABLE product (name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, price DOUBLE PRECISION NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_category_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04ADBE6903FD ON product (product_category_id)');
        $this->addSql('CREATE UNIQUE INDEX product_name_idx ON product (name)');
        $this->addSql('CREATE TABLE product_category (name VARCHAR(255) NOT NULL, id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX product_category_name_idx ON product_category (name)');
        $this->addSql('CREATE TABLE product_in_order (product_quantity INT NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_746CE7714584665A ON product_in_order (product_id)');
        $this->addSql('CREATE INDEX IDX_746CE7718D9F6D38 ON product_in_order (order_id)');
        $this->addSql('CREATE TABLE shop (name VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, street VARCHAR(255) NOT NULL, build VARCHAR(255) NOT NULL, id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX shop_name_idx ON shop (name)');
        $this->addSql('CREATE TABLE shop_has_supplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, shop_id SMALLINT NOT NULL, supplier_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9729F1D84D16C4DD ON shop_has_supplier (shop_id)');
        $this->addSql('CREATE INDEX IDX_9729F1D82ADD6D8C ON shop_has_supplier (supplier_id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993984D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993986BF700BD FOREIGN KEY (status_id) REFERENCES order_status (id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADBE6903FD FOREIGN KEY (product_category_id) REFERENCES product_category (id)');
        $this->addSql('ALTER TABLE product_in_order ADD CONSTRAINT FK_746CE7714584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_in_order ADD CONSTRAINT FK_746CE7718D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id)');
        $this->addSql('ALTER TABLE shop_has_supplier ADD CONSTRAINT FK_9729F1D84D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id)');
        $this->addSql('ALTER TABLE shop_has_supplier ADD CONSTRAINT FK_9729F1D82ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993984D16C4DD');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993986BF700BD');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADBE6903FD');
        $this->addSql('ALTER TABLE product_in_order DROP CONSTRAINT FK_746CE7714584665A');
        $this->addSql('ALTER TABLE product_in_order DROP CONSTRAINT FK_746CE7718D9F6D38');
        $this->addSql('ALTER TABLE shop_has_supplier DROP CONSTRAINT FK_9729F1D84D16C4DD');
        $this->addSql('ALTER TABLE shop_has_supplier DROP CONSTRAINT FK_9729F1D82ADD6D8C');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_category');
        $this->addSql('DROP TABLE product_in_order');
        $this->addSql('DROP TABLE shop');
        $this->addSql('DROP TABLE shop_has_supplier');
    }
}
