<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124233105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shop_has_supplier DROP CONSTRAINT fk_9729f1d84d16c4dd');
        $this->addSql('ALTER TABLE shop_has_supplier DROP CONSTRAINT fk_9729f1d82add6d8c');
        $this->addSql('DROP TABLE shop_has_supplier');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shop_has_supplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, shop_id SMALLINT NOT NULL, supplier_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_9729f1d84d16c4dd ON shop_has_supplier (shop_id)');
        $this->addSql('CREATE INDEX idx_9729f1d82add6d8c ON shop_has_supplier (supplier_id)');
        $this->addSql('ALTER TABLE shop_has_supplier ADD CONSTRAINT fk_9729f1d84d16c4dd FOREIGN KEY (shop_id) REFERENCES shop (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shop_has_supplier ADD CONSTRAINT fk_9729f1d82add6d8c FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
